Importing Neccessary Libraries

In [98]:
#importing necessary libraries
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import os
import tsfel
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import numpy as np

Paths to the library

In [120]:
#paths to test data and training data
folder = '/Users/shreya/Documents/fork-it/Task_4/data.csv'

In [124]:
data = pd.read_csv(folder)
data = data.rename(columns={
    'ax (m/s^2)': 'accx',
    'ay (m/s^2)': 'accy',
    'az (m/s^2)': 'accz',
    'aT (m/s^2)': 'accT'
})
print(data.head())

feature_columns = ['accx', 'accy', 'accz']
label_column = 'label'

       time    accx    accy    accz   accT    label
0  9.009992  3.1378 -1.8697  1.7189  4.037  WALKING
1  9.015175  2.7793 -2.1430  1.5280  3.828  WALKING
2  9.019427  2.3820 -2.3886  1.4851  3.686  WALKING
3  9.024446  1.9315 -2.6075  1.4817  3.567  WALKING
4  9.029707  1.5816 -2.6659  1.4791  3.435  WALKING


In [125]:
X = data[feature_columns]
y = data[label_column]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [129]:
model = DecisionTreeClassifier(max_leaf_nodes=10, random_state=42)
model.fit(X_train, y_train)

DecisionTreeClassifier(max_leaf_nodes=10, random_state=42)

In [130]:
y_pred = model.predict(X_test)

In [131]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted', zero_division=0)
recall = recall_score(y_test, y_pred, average='weighted', zero_division=0)
conf_matrix = confusion_matrix(y_test, y_pred)

In [132]:
print(f'Accuracy: {accuracy:.2f}')
print(f'Precision: {precision:.2f}')
print(f'Recall: {recall:.2f}')
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.51
Precision: 0.40
Recall: 0.51
Confusion Matrix:
[[ 703  209  106    2    0    0]
 [  92  808  186   85    0    0]
 [  72  233  603   50    0    0]
 [   0   21   26 1138    0    0]
 [   0   10   29  976    0    0]
 [   0   22   37 1015    0    0]]


In [75]:
plt.figure(figsize=(100,100))
plot_tree(model,filled=True,feature_names=['accx','accy','accz'],class_names=model.classes_)
plt.title("Decision Tree Visualization")
plt.show()

Normalizing the Data

In [134]:
norm_data = '/Users/shreya/Documents/fork-it/Task_4/data.csv'
norm_df = pd.read_csv(norm_data)

In [142]:
norm_df = norm_df.rename(columns={'ax (m/s^2)': 'accx', 'ay (m/s^2)': 'accy', 'az (m/s^2)':'accz', 'aT (m/s^2)':'accT'})
print(norm_df.head())

       time    accx    accy    accz   accT    label
0  9.009992  3.1378 -1.8697  1.7189  4.037  WALKING
1  9.015175  2.7793 -2.1430  1.5280  3.828  WALKING
2  9.019427  2.3820 -2.3886  1.4851  3.686  WALKING
3  9.024446  1.9315 -2.6075  1.4817  3.567  WALKING
4  9.029707  1.5816 -2.6659  1.4791  3.435  WALKING


In [144]:
columns_to_normalize = ['accx', 'accy', 'accz', 'accT']
scaler = MinMaxScaler(feature_range=(-1, 1))
normalized_data = scaler.fit_transform(norm_df[columns_to_normalize])
normalized_df = pd.DataFrame(normalized_data, columns=columns_to_normalize)
final_df = pd.concat([normalized_df,norm_df.drop(columns=columns_to_normalize)], axis=1)
print(final_df.head())

       accx      accy      accz      accT      time    label
0 -0.212516  0.056439  0.037447 -0.694515  9.009992  WALKING
1 -0.231392  0.029629  0.023933 -0.710338  9.015175  WALKING
2 -0.252311  0.005537  0.020897 -0.721089  9.019427  WALKING
3 -0.276032 -0.015935  0.020656 -0.730098  9.024446  WALKING
4 -0.294456 -0.021664  0.020472 -0.740092  9.029707  WALKING


In [146]:
feature_columns = ['accx', 'accy', 'accz']
label_column = 'label'

In [147]:
X_n = final_df[feature_columns]
y_n = final_df[label_column]

X_ntrain, X_ntest, y_ntrain, y_ntest = train_test_split(X_n, y_n, test_size=0.2, random_state=42)

In [148]:
model2 = DecisionTreeClassifier(max_leaf_nodes=10, random_state=42)
model2.fit(X_ntrain, y_ntrain)

DecisionTreeClassifier(max_leaf_nodes=10, random_state=42)

In [149]:

y_pred_norm = model.predict(X_ntest)

In [150]:
accuracy = accuracy_score(y_ntest, y_pred_norm)
precision = precision_score(y_ntest, y_pred_norm,average='weighted')
recall = recall_score(y_ntest, y_pred_norm, average='weighted')
conf_matrix = confusion_matrix(y_ntest, y_pred_norm)
print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.17
Precision: 0.03
Recall: 0.17
Confusion Matrix:
[[   0    0    0 1020    0    0]
 [   0    0    0 1171    0    0]
 [   0    0    0  958    0    0]
 [   3   62   51 1069    0    0]
 [   8   92   48  867    0    0]
 [   6   61   58  949    0    0]]


/Users/shreya/Documents/fork-it/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
